apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: www-artist
  description: Artist main website
spec:
  type: website
  lifecycle: production
  owner: arcadians
  system: artist-engagement-portal
